### ISSUE TITLE
didFinishLoadForFrame doesn't fire when CSS is applied

### ISSUE THREAD

**Issue by kneath** [kneath/learning-webviews#1]
_I know you're probably assuming this is an iOS project, but I'm not mentally challenged  — I want to build a Mac app._

Right now `WebViewJavascriptBridge` sets the frameLoad delegate, and defines `(void)webView:(WebView *)webView didFinishLoadForFrame:(WebFrame *)frame` to handle frame loads. I added a quick `NSLog` to make sure everything's working just to make sure — https://github.com/kneath/learning-webviews/blob/c7c3e98888e99772b6ab6452a8ec2e0a72989766/Dropsack/WebViewJavascriptBridge.m#L255. And it totally does work, **if** you remove the `<link />` to the CSS [here](https://github.com/kneath/learning-webviews/blob/c7c3e98888e99772b6ab6452a8ec2e0a72989766/Dropsack/HTML/recipe.html#L6).

Why is this? The only thing I could find on the internets:
- No one who writes iOS apps knows what a delegate is. My delegate is set. For real.
- Maybe fonts stop it from loading? I've also tried removing all font declarations, no go.

**Comment by tenderlove** [comment]
Shot in the dark, but does it need to be `styles/compiled.css`?  Maybe you're not getting the delegate fired because it didn't finish loading?

**Comment by kneath** [comment]
@tenderlove I started out that way, but it needs to be in the same namespace due to the way Xcode does resource bundling (also the css totally loads the way it is now)

**Comment by kneath** [comment]
![image](https://cloud.githubusercontent.com/assets/1354/5686357/f0e20ef4-97f6-11e4-9998-74895d6d6a7e.png)

:sparkling_heart: @hunterbridges
